Drop py2 in Travis CI.
google/mobly pull request #679
Opened 2020-09-01 13:20 UTC by eric100lin

Python 2 is no longer supported, let's only run unit tests in py3.
https://pythonclock.org/

2020-09-03 03:00 UTC, xpconanfan requested changes

2020-09-03 03:11 UTC, eric100lin commented on mobly/utils.py
> +import portpicker
Imports Python standard library at the top-level, then imports third-party modules or packages.
Follow Google's Python style guide: https://google.github.io/styleguide/pyguide.html#313-imports-formatting

2021-01-07 09:27 UTC, xpconanfan requested changes
We should also remove any usage of
`from __future__ import ..`
```
from future import standard_library
standard_library.install_aliases()
```
and the `six` module

2021-01-07 09:29 UTC, xpconanfan requested changes
Also probably need to remove any usage of the `futures` module, which is included by `setup.py`

2021-01-08 09:33 UTC, xpconanfan commented
Let's remove those in a separate PR

2021-01-08 09:39 UTC, xpconanfan approved these changes

2021-01-08 09:40 UTC, merged