Add a retry mechanism for the ADB command "root"
google/mobly pull request #687
Opened 2020-12-09 09:48 UTC by chuanhsiao

Sometimes Error "adb: unable to connect for root: closed" occurs when calling AndroidDevice.reboot(), this mechanism attempts to avoid this error causes a test to be stopped.

2020-12-10 04:02 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/687)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @chuanhsiao)

___
*[mobly/controllers/android_device_lib/adb.py, line 466 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9aOaX-Q1peRPm-eSQ:-MO9aOaX-Q1peRPm-eSR:b-4ol9er) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L466)):*
> ```Python
>             return self._execute_adb_and_process_stdout(
>                 'shell', instrumentation_command, shell=False, handler=handler)
>                 
> ```

random dots?
___
*[mobly/controllers/android_device_lib/adb.py, line 470 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9o7m4DFB-3_gyhTP9:-MO9o7m4DFB-3_gyhTPA:biq8twm) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L470)):*
> ```Python
>         """Enables ADB root mode on the device.
> 
>         This method will retry to execute the command "adb root" when an
> ```

Need some reasoning for having this special method for `root`


<!-- Sent from Reviewable.io -->

2020-12-10 23:30 UTC, chuanhsiao reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/687)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @xpconanfan)

___
*[mobly/controllers/android_device_lib/adb.py, line 466 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9aOaX-Q1peRPm-eSQ:-MODzSze5IWQ3jjmCUig:ba3dfob) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L466)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

random dots?
</blockquote></details>

Removed
___
*[mobly/controllers/android_device_lib/adb.py, line 470 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9o7m4DFB-3_gyhTP9:-MODzSfb2HpXmUQEf3KE:b-896fix) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L470)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Need some reasoning for having this special method for `root`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-25 02:44 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/687)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chuanhsiao)

___
*[mobly/controllers/android_device_lib/adb.py, line 470 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9o7m4DFB-3_gyhTP9:-MPMltdb92nVl03ShjxY:bcl5c0k) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L470)):*
<details><summary><i>Previously, chuanhsiao wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this explains what the code does, not the reasoning...
many commands may throw this error, why are we adding a retry for this one?


<!-- Sent from Reviewable.io -->

2021-01-06 09:44 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/687)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chuanhsiao)

___
*[mobly/controllers/android_device_lib/adb.py, line 472 at r2](https://reviewable.io/reviews/google/mobly/687#-MQM3mqCDVIzILM-k7ER:-MQM3mqDCqiX7nOajXCJ:b-15e7ku) ([raw file](https://github.com/google/mobly/blob/6af5ffc96ccc4e256bec2056921e9d6ea8e95141/mobly/controllers/android_device_lib/adb.py#L472)):*
> ```Python
>         This method will retry to execute the command "adb root" when an
>         AdbError occurs, since sometimes the error "adb: unable to connect
>         for root: closed" is raised when calling AndroidDevice.reboot().
> ```

a few minor things
* I think you mean `adb.reboot()`, not `AndroidDevice.reboot()`
* Use `code` instead of quotation marks for marking code.


<!-- Sent from Reviewable.io -->

2021-01-06 11:48 UTC, chuanhsiao reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/687)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chuanhsiao)

___
*[mobly/controllers/android_device_lib/adb.py, line 470 at r1](https://reviewable.io/reviews/google/mobly/687#-MO9o7m4DFB-3_gyhTP9:-MQMWDtD4aw0AQgz7bWj:b-n57pss) ([raw file](https://github.com/google/mobly/blob/e959887371d0fb4bd7b6de116431fc49f35319a3/mobly/controllers/android_device_lib/adb.py#L470)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

this explains what the code does, not the reasoning...
many commands may throw this error, why are we adding a retry for this one?
</blockquote></details>

As talked, 
done
___
*[mobly/controllers/android_device_lib/adb.py, line 472 at r2](https://reviewable.io/reviews/google/mobly/687#-MQM3mqCDVIzILM-k7ER:-MQMWShgBDcQmCfT7Ipr:bb6un1j) ([raw file](https://github.com/google/mobly/blob/6af5ffc96ccc4e256bec2056921e9d6ea8e95141/mobly/controllers/android_device_lib/adb.py#L472)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

a few minor things
* I think you mean `adb.reboot()`, not `AndroidDevice.reboot()`
* Use `code` instead of quotation marks for marking code.

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-01-07 01:52 UTC, chuanhsiao commented
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
>  **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogle%2Fmobly%2Fpull%2F687) for more info**.

2021-01-07 01:52 UTC, closed without merging