Fix the behavior of `SnippetClient#is_alive`.
google/mobly pull request #732
Opened 2021-03-12 08:06 UTC by xpconanfan

`SnippetClient#is_alive` returns True even when it is paused, which propagates to the `SnippetManagermentService`. This is in direct contradiction to the definition of `Service#is_alive`.

This change fixes the behavior, and cleans up the hacky code that attempted to cover this behavior.

Fixes #665

2021-03-15 08:12 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/732)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @xpconanfan)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 268 at r1](https://reviewable.io/reviews/google/mobly/732#-MVov5-6DRhDDgomjfVa:-MVov5-78y79ZdOe_6_F:bxlsx4l) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L268)):*
> ```
> self._adb
> ```
I think here might better to use `self._ad.adb`?
___
*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 89 at r1](https://reviewable.io/reviews/google/mobly/732#-MVodiqe3EENMnLd2UoG:-MVodiqe3EENMnLd2UoH:b-jjjx2y) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L89)):*
> ```
> mock_conn.close.side_effect = Exception('ha')
> ```
The same issue as `snippet_client_test`:
```
tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py::JsonRpcClientBaseTest::test_disconnect_raises
  /mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/_pytest/unraisableexception.py:77: PytestUnraisableExceptionWarning: Exception ignored in: <function JsonRpcClientBase.__del__ at 0x7f568a8a9700>
  
  Traceback (most recent call last):
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 148, in __del__
      self.disconnect()
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 258, in disconnect
      self._conn.close()
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1088, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1091, in _mock_call
      return _mock_self._execute_mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1148, in _execute_mock_call
      raise effect
  Exception: ha
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

I would like to make the second call return None:
```
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_conn.close.side_effect = [Exception('ha'), None]
```
___
*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 93 at r1](https://reviewable.io/reviews/google/mobly/732#-MVosF3vArrPhKumPMD3:-MVosF3w1cxyFx8Cuayv:bqfszm7) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L93)):*
> ```Python
>       client.disconnect()
>     client.clear_host_port.assert_called_once_with()
> ```

We might need some test methods for `clear_host_port()`.

For example,

```
  def test_clear_host_port_positive(self):
    client = FakeRpcClient()
    client.host_port = 1
    client.clear_host_port()
    client._ad.adb.forward.assert_called_once_with(['--remove', 'tcp:1'])
    self.assertIsNone(client.host_port)

  def test_clear_host_port_negative(self):
    client = FakeRpcClient()
    client.clear_host_port()
    client._ad.adb.forward.assert_not_called()
```
___
*[tests/mobly/controllers/android_device_lib/snippet_client_test.py, line 170 at r1](https://reviewable.io/reviews/google/mobly/732#-MVo_s0S7FSkYMb-PJTE:-MVo_s0S7FSkYMb-PJTF:bppgad9) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/snippet_client_test.py#L170)):*
> ```Python
> 
>   @mock.patch('socket.create_connection')
>   def test_snippet_stop_app_raises(self, mock_create_connection):
> ```

Here we need to keep "Explicitly making the second side_effect noop to avoid uncaught exception" because the destructor(`JsonRpcClientBase.__del__`) calls `self.disconnect()`. The "warnings" shows with this test codes (Yes, it just show warnings):
```
============================================================================================ warnings summary =============================================================================================
tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py::JsonRpcClientBaseTest::test_disconnect_raises
tests/mobly/controllers/android_device_lib/snippet_client_test.py::SnippetClientTest::test_snippet_stop_app_raises
  /mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/_pytest/unraisableexception.py:77: PytestUnraisableExceptionWarning: Exception ignored in: <function JsonRpcClientBase.__del__ at 0x7f0b4d7fe700>
  
  Traceback (most recent call last):
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 148, in __del__
      self.disconnect()
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 258, in disconnect
      self._conn.close()
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1088, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1091, in _mock_call
      return _mock_self._execute_mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1148, in _execute_mock_call
      raise effect
  Exception: ha
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

I think here we can just mock `JsonRpcClientBase.disconnect` because it is tested in jsonrpc_client_base_test.py.    
This is my suggestions changes:

```
  @mock.patch('socket.create_connection')
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect, _):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    adb_proxy = mock.MagicMock()
    adb_proxy.shell.return_value = b'OK (0 tests)'
    client = self._make_client(adb_proxy)
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```

1. Use `mock.patch.object` to patch `disconnect` method from base class
2. Use `_` to replace un-reference `mock_create_connection` variable
3. Remove the `adb_proxy.forward.assert_called_once_with` assert
4. Remove `client.host_port = 1` and `adb_proxy`


<!-- Sent from Reviewable.io -->

2021-03-15 08:12 UTC, eric100lin reviewed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/732)* status: all files reviewed, 4 unresolved discussions (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2021-03-15 08:17 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/732)* status: all files reviewed, 4 unresolved discussions (waiting on @xpconanfan)

___
*[tests/mobly/controllers/android_device_lib/snippet_client_test.py, line 170 at r1](https://reviewable.io/reviews/google/mobly/732#-MVo_s0S7FSkYMb-PJTE:-MVowxOS3-YNEZRPN8Af:b-npetst) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/snippet_client_test.py#L170)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Here we need to keep "Explicitly making the second side_effect noop to avoid uncaught exception" because the destructor(`JsonRpcClientBase.__del__`) calls `self.disconnect()`. The "warnings" shows with this test codes (Yes, it just show warnings):
```
============================================================================================ warnings summary =============================================================================================
tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py::JsonRpcClientBaseTest::test_disconnect_raises
tests/mobly/controllers/android_device_lib/snippet_client_test.py::SnippetClientTest::test_snippet_stop_app_raises
  /mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/_pytest/unraisableexception.py:77: PytestUnraisableExceptionWarning: Exception ignored in: <function JsonRpcClientBase.__del__ at 0x7f0b4d7fe700>
  
  Traceback (most recent call last):
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 148, in __del__
      self.disconnect()
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 258, in disconnect
      self._conn.close()
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1088, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1091, in _mock_call
      return _mock_self._execute_mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1148, in _execute_mock_call
      raise effect
  Exception: ha
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

I think here we can just mock `JsonRpcClientBase.disconnect` because it is tested in jsonrpc_client_base_test.py.    
This is my suggestions changes:

```
  @mock.patch('socket.create_connection')
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect, _):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    adb_proxy = mock.MagicMock()
    adb_proxy.shell.return_value = b'OK (0 tests)'
    client = self._make_client(adb_proxy)
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```

1. Use `mock.patch.object` to patch `disconnect` method from base class
2. Use `_` to replace un-reference `mock_create_connection` variable
3. Remove the `adb_proxy.forward.assert_called_once_with` assert
4. Remove `client.host_port = 1` and `adb_proxy`
</blockquote></details>

Update my suggestion codes:

```
  @mock.patch('socket.create_connection')
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect, _):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    client = self._make_client()
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```


<!-- Sent from Reviewable.io -->

2021-03-15 08:19 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/732)* status: all files reviewed, 4 unresolved discussions (waiting on @xpconanfan)

___
*[tests/mobly/controllers/android_device_lib/snippet_client_test.py, line 170 at r1](https://reviewable.io/reviews/google/mobly/732#-MVo_s0S7FSkYMb-PJTE:-MVoxuy_9hRrq4gKjLIg:b-4rzjoi) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/snippet_client_test.py#L170)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Update my suggestion codes:

```
  @mock.patch('socket.create_connection')
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect, _):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    client = self._make_client()
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```
</blockquote></details>

The mock to `socket.create_connection` can also be removed:

```
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    client = self._make_client()
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```


<!-- Sent from Reviewable.io -->

2021-03-16 17:37 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/732)* status: all files reviewed, 4 unresolved discussions (waiting on @eric100lin)

___
*[mobly/controllers/android_device_lib/jsonrpc_client_base.py, line 268 at r1](https://reviewable.io/reviews/google/mobly/732#-MVov5-6DRhDDgomjfVa:-MVw4t0R3KL4M2gNf6uo:b-896fix) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/mobly/controllers/android_device_lib/jsonrpc_client_base.py#L268)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> self._adb
> ```
I think here might better to use `self._ad.adb`?
</blockquote></details>

Done.
___
*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 89 at r1](https://reviewable.io/reviews/google/mobly/732#-MVodiqe3EENMnLd2UoG:-MVw53sTA9UpIFWAHTe5:b5oph8r) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L89)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> mock_conn.close.side_effect = Exception('ha')
> ```
The same issue as `snippet_client_test`:
```
tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py::JsonRpcClientBaseTest::test_disconnect_raises
  /mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/_pytest/unraisableexception.py:77: PytestUnraisableExceptionWarning: Exception ignored in: <function JsonRpcClientBase.__del__ at 0x7f568a8a9700>
  
  Traceback (most recent call last):
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 148, in __del__
      self.disconnect()
    File "/mnt/sda/mobly/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 258, in disconnect
      self._conn.close()
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1088, in __call__
      return _mock_self._mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1091, in _mock_call
      return _mock_self._execute_mock_call(*args, **kwargs)
    File "/mnt/sda/mobly/.tox/py3/lib/python3.8/site-packages/mock/mock.py", line 1148, in _execute_mock_call
      raise effect
  Exception: ha
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

I would like to make the second call return None:
```
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_conn.close.side_effect = [Exception('ha'), None]
```
</blockquote></details>

Done.

Interesting. I don't see the warning when running with tox.
Do we need to add extra param in the tox config for warnings to always show?
___
*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 93 at r1](https://reviewable.io/reviews/google/mobly/732#-MVosF3vArrPhKumPMD3:-MVw5U5J5bgTQz1VQoxs:b-896fix) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L93)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

We might need some test methods for `clear_host_port()`.

For example,

```
  def test_clear_host_port_positive(self):
    client = FakeRpcClient()
    client.host_port = 1
    client.clear_host_port()
    client._ad.adb.forward.assert_called_once_with(['--remove', 'tcp:1'])
    self.assertIsNone(client.host_port)

  def test_clear_host_port_negative(self):
    client = FakeRpcClient()
    client.clear_host_port()
    client._ad.adb.forward.assert_not_called()
```
</blockquote></details>

Done.
___
*[tests/mobly/controllers/android_device_lib/snippet_client_test.py, line 170 at r1](https://reviewable.io/reviews/google/mobly/732#-MVo_s0S7FSkYMb-PJTE:-MVw66Ew7yi3Q_x40fy2:b-896fix) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/snippet_client_test.py#L170)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

The mock to `socket.create_connection` can also be removed:

```
  @mock.patch.object(jsonrpc_client_base.JsonRpcClientBase, 'disconnect')
  def test_snippet_stop_app_raises(self, mock_disconnect):
    # Explicitly making the second side_effect noop to avoid uncaught exception
    # when `__del__` is called after the test is done, which triggers
    # `disconnect`.
    mock_disconnect.side_effect = [Exception('ha'), None]
    client = self._make_client()
    with self.assertRaisesRegex(Exception, 'ha'):
      client.stop_app()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-17 05:35 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly/732#-:-MVyfUWD08bKwI1RyKfj:bnfp4nl)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py, line 89 at r1](https://reviewable.io/reviews/google/mobly/732#-MVodiqe3EENMnLd2UoG:-MVyecni2NOQXmqoycmk:byca330) ([raw file](https://github.com/google/mobly/blob/5cda167f6efb878b5e32254e658d0278a095ebc2/tests/mobly/controllers/android_device_lib/jsonrpc_client_base_test.py#L89)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.

Interesting. I don't see the warning when running with tox.
Do we need to add extra param in the tox config for warnings to always show?
</blockquote></details>

Hmm, I am not sure why it not show.
I only run it by `tox` command in venv.
My tox is v3.21.0.


<!-- Sent from Reviewable.io -->

2021-03-17 19:26 UTC, xpconanfan commented
Travis CI is still broken. Forcing merge.

2021-03-17 19:27 UTC, merged