Support native repeat and retry in Mobly.
google/mobly pull request #734
Opened 2021-04-17 01:20 UTC by xpconanfan

* Provides decorators for users to mark test cases for repeat and retry.
* Adds new attributes to the TestResultRecord for associating retry test records.
* Refactors existing code to support the repeat/retry behavior.

2021-04-19 08:23 UTC, eric100lin requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: all files reviewed, 8 unresolved discussions (waiting on @xianyuanjia and @xpconanfan)

___
*[mobly/base_test.py, line 100 at r1](https://reviewable.io/reviews/google/mobly/734#-MYdAksw54zNO7MG9UTf:-MYdAksw54zNO7MG9UTg:b-j6c8c1) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L100)):*
> ```
> maximun
> ```
nit: typo here, the last char should be 'm'
maximum
___
*[mobly/base_test.py, line 637 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcu-In9hSxG9D2bWkQ:-MYcu-In9hSxG9D2bWkR:bkyqrey) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L637)):*
> ```
>   def exec_one_test_with_retry(self, test_name, test_method, max_retry_count):
> ```
Might need to write the pydoc for this method.
___
*[mobly/base_test.py, line 651 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd4J8n5EPXuQF5UVDb:-MYd4J8n5EPXuQF5UVDc:beeyn9j) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L651)):*
> ```
> new_record
> ```
Do we want to let Mobly user to know the new_record for the retry run?
(ex1: if user want to call `BaseTestClass.record_data` for recording data for the current test method,
it will overwrite the previous data because each retry they only have the same record)
(ex2: user might want to get the retry number in their test method to print some logs)
If yes, we might need to update `BaseTestClass.current_test_info.record`?

It might be great if we log some debugging info for each retry round.
___
*[mobly/base_test.py, line 655 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd1R9-EyUCAJCmf0Qe:-MYd1R9-EyUCAJCmf0Qf:b-vh6u2c) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L655)):*
> ```
> return previous_record
> ```
Do we really need to return this record?
I don't see the caller side dealing with the return value.
___
*[mobly/base_test.py, line 672 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcmowD8t--A6HvqEfI:-MYcmowD8t--A6HvqEfJ:b-ta9vbe) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L672)):*
> ```
>     """
> ```
Needs a "Returns" section for the pydoc of `exec_one_test`.
___
*[mobly/records.py, line 333 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd96Dg6G9QX00zM-hx:-MYd96Dg6G9QX00zM-hy:bmjkhoj) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L333)):*
> ```
>     self.signature = None
>     self.retry_parent = None
> ```
Do we want to update `TestResultRecord#to_dict` to put the newly created attributes into the test_summary.yaml?
___
*[mobly/records.py, line 370 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcjIoX6SwXmoJMFX3n:-MYcjIoX6SwXmoJMFX3o:b-2c4tht) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L370)):*
> ```Python
>     """
>     self.begin_time = utils.get_current_epoch_time()
>     self.signature = '%s-%s' % (self.test_name, self.begin_time)
> ```

Might need a test case to make sure the `self.signature` generation logic, for example: `test_signature` in tests/mobly/records_test.py.
___
*[tests/mobly/base_test_test.py, line 2269 at r1](https://reviewable.io/reviews/google/mobly/734#-MYdCLQj0DqF-nbJW2My:-MYdCLQj0DqF-nbJW2Mz:b-gbbqf4) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/tests/mobly/base_test_test.py#L2269)):*
> ```
> Someting
> ```
nit: typo here. should be
Something


<!-- Sent from Reviewable.io -->

2021-04-21 03:45 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: all files reviewed, 6 unresolved discussions (waiting on @eric100lin and @xianyuanjia)

___
*[mobly/base_test.py, line 637 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcu-In9hSxG9D2bWkQ:-MYmSfVu6GlvInj9ulap:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L637)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
>   def exec_one_test_with_retry(self, test_name, test_method, max_retry_count):
> ```
Might need to write the pydoc for this method.
</blockquote></details>

Done.
___
*[mobly/base_test.py, line 651 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd4J8n5EPXuQF5UVDb:-MYmSmgc55cEtVhBsCVG:b-9v6k0x) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L651)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> new_record
> ```
Do we want to let Mobly user to know the new_record for the retry run?
(ex1: if user want to call `BaseTestClass.record_data` for recording data for the current test method,
it will overwrite the previous data because each retry they only have the same record)
(ex2: user might want to get the retry number in their test method to print some logs)
If yes, we might need to update `BaseTestClass.current_test_info.record`?

It might be great if we log some debugging info for each retry round.
</blockquote></details>

not sure what you mean.
each retry iteration already has its own dedicated record object and entry in the summary yamlright?
___
*[mobly/base_test.py, line 655 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd1R9-EyUCAJCmf0Qe:-MYmSz1EBgMRsjlAyi0-:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L655)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
> return previous_record
> ```
Do we really need to return this record?
I don't see the caller side dealing with the return value.
</blockquote></details>

Done.
___
*[mobly/base_test.py, line 672 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcmowD8t--A6HvqEfI:-MYmTVkb7UMfKxEv07mo:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L672)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
>     """
> ```
Needs a "Returns" section for the pydoc of `exec_one_test`.
</blockquote></details>

Done.
___
*[mobly/records.py, line 333 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd96Dg6G9QX00zM-hx:-MYmURML0tU8seyFtM8D:b-o7vuhc) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L333)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

> ```
>     self.signature = None
>     self.retry_parent = None
> ```
Do we want to update `TestResultRecord#to_dict` to put the newly created attributes into the test_summary.yaml?
</blockquote></details>

Good catch! Done.
___
*[mobly/records.py, line 370 at r1](https://reviewable.io/reviews/google/mobly/734#-MYcjIoX6SwXmoJMFX3n:-MYmX-IP5NBilPdFRoxc:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L370)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Might need a test case to make sure the `self.signature` generation logic, for example: `test_signature` in tests/mobly/records_test.py.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-21 09:57 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @eric100lin, @xianyuanjia, and @xpconanfan)

___
*[mobly/base_test.py, line 651 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd4J8n5EPXuQF5UVDb:-MYnqbp41trfKsyuJLnK:bmq96ei) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/base_test.py#L651)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

not sure what you mean.
each retry iteration already has its own dedicated record object and entry in the summary yamlright?
</blockquote></details>

Oops, you are totally right.


<!-- Sent from Reviewable.io -->

2021-04-21 10:08 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @eric100lin, @xianyuanjia, and @xpconanfan)

___
*[mobly/records.py, line 333 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd96Dg6G9QX00zM-hx:-MYnrRRGBdOJ9axwSjN5:bjh2t53) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L333)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Good catch! Done.
</blockquote></details>

Sorry, it seems "signature" or "retry_parent" still not in test_summary.yaml.
I wrote a simple script to run with this PR but the results seems no "signature" or "retry_parent":
https://gist.github.com/eric100lin/d6592a5d00e1053a2ab3b2e1636d49c6


<!-- Sent from Reviewable.io -->

2021-04-23 03:02 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xianyuanjia)

___
*[mobly/records.py, line 333 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd96Dg6G9QX00zM-hx:-MYrP14n2pbFu_ywSjea:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L333)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Sorry, it seems "signature" or "retry_parent" still not in test_summary.yaml.
I wrote a simple script to run with this PR but the results seems no "signature" or "retry_parent":
https://gist.github.com/eric100lin/d6592a5d00e1053a2ab3b2e1636d49c6
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 03:03 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xianyuanjia)

___
*[mobly/records.py, line 333 at r1](https://reviewable.io/reviews/google/mobly/734#-MYd96Dg6G9QX00zM-hx:-MYwfY1-1HcGrCcCVWCu:b-896fix) ([raw file](https://github.com/google/mobly/blob/33d5d72d4e6286ff89b38e1bf1531561eca1ca16/mobly/records.py#L333)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 08:45 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/734#-:-MYxtGIn8kcPY9jBfFcg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xianyuanjia)



<!-- Sent from Reviewable.io -->

2021-04-23 20:30 UTC, merged