Fix flake8 warning (#741)
google/mobly pull request #745
Opened 2021-05-06 12:15 UTC by johnklee

Fix flake8 warning (part2)

2021-05-06 12:20 UTC, johnklee commented on mobly/controllers/android_device.py
> +    except Exception:
Fix according to Flake8 rule [E722](https://www.flake8rules.com/rules/E722.html)
```
Do not use bare except, specify exception instead
```

2021-05-06 12:22 UTC, johnklee commented on mobly/controllers/android_device_lib/snippet_client.py
> +         line.startswith('SNIPPET ')):
Fix according to Flake8 rule [E129](https://www.flake8rules.com/rules/E129.html)
> Visually indented line with same indent as next logical line

2021-05-06 12:24 UTC, johnklee commented on mobly/controllers/attenuator.py
> -    instances = attenuation_device.open(config[KEY_ADDRESS], config[KEY_PORT])
Fix according to Flake8 rule [F841](https://www.flake8rules.com/rules/F841.html)
> F841 local variable 'instances' is assigned to but never used

2021-05-06 12:25 UTC, johnklee commented on mobly/controllers/attenuator_lib/telnet_scpi_client.py
> +        [_ascii_string(r'\S+' + self.rx_cmd_separator)], 1)
Fix according to Flake8 rule [W605](https://www.flake8rules.com/rules/W605.html)
> W605 invalid escape sequence '\S'

2021-05-06 12:26 UTC, johnklee commented on mobly/controllers/sniffer_lib/local/tshark.py
> +    return "local-tshark-{0}-ch{0}".format(self._interface)
Need clarification to see what we expect from the second argument. Above is just a temporal fix.

2021-05-10 05:58 UTC, xpconanfan requested changes

2021-05-10 09:13 UTC, johnklee commented
> I think we should leave the monsoon, attenuator, and sniffer code as is.
> We plan to remove these code from Mobly repo as they are pretty old and not really used.

Thanks for the notification. Done in below commit:
https://github.com/johnklee/mobly/commit/f856b556b351d715ae6d652445a36e0fcdb4c784

2021-05-10 09:31 UTC, xpconanfan requested changes
I still see files for monsoon, sniffer lib, and iperf, which should be removed from the PR.

2021-05-10 09:46 UTC, johnklee commented
> I still see files for monsoon, sniffer lib, and iperf, which should be removed from the PR.

Sorry for the inconvenience. I restore those files in below commit:
https://github.com/johnklee/mobly/commit/f5aa6e1bb78dea7af17a4007c84e1bbf1b8859f6

2021-05-10 11:11 UTC, xpconanfan approved these changes

2021-05-10 11:11 UTC, merged