Supports `universal_newlines` as argument in utils#run_command
google/mobly pull request #749
Opened 2021-05-20 09:41 UTC by troub1emaker-sys

2021-05-20 09:53 UTC, xpconanfan requested changes
Let's add some unit tests for this addition

2021-05-20 10:26 UTC, troub1emaker-sys commented
Added some unittest.

2021-05-21 02:24 UTC, xpconanfan requested changes
Unit tests are failing. Please fix.

2021-05-21 07:34 UTC, xpconanfan approved these changes

2021-05-21 07:35 UTC, merged