Inspect class instead of class instance to get test methods list.
google/mobly pull request #762
Opened 2021-08-16 19:56 UTC by xianyuanjia

This prevents inspect.getmembers from calling the properties of given test class. 

e.g.
```
>>>class Foo():
...   @property
...   def bar(self):
...       print('Called')

>>> inspect.getmembers(Foo(), callable)
Called
[...]
>>> getattr(Foo(), 'bar')
Called
'baz'

>>> inspect.getmembers(Foo, callable)
[...]
>>> getattr(Foo, 'bar')
<property object at 0x7f7c7463cb30>
```

2021-08-20 02:17 UTC, xpconanfan requested changes
Can we add a test for the use case we are trying to enable here?

2021-08-20 20:20 UTC, xianyuanjia reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/google/mobly/762#-:-Mh_D4YYDcDBq5wrUq8u:b-896fix)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @eric100lin)



<!-- Sent from Reviewable.io -->

2021-08-23 01:54 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/762#-:-MhkhksQ1q0u1wW-ikm1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xianyuanjia)



<!-- Sent from Reviewable.io -->

2021-08-23 02:58 UTC, eric100lin commented
According to the cpython source codes:    
https://github.com/python/cpython/blob/3.9/Lib/inspect.py#L351

When using inspect with class instance:`inspect.getmembers(Foo(), callable)`
It will call `getattr(foo_instance, key)` on all keys from `dir(foo_instance)`, therefore the `bar` property getter will be called.

When using  inspect with class type: `inspect.getmembers(Foo, callable)`
It will call `getattr(Foo, key)` on all keys from `dir(Foo)`, the `bar` property getter will not be called.

2021-08-23 05:20 UTC, xpconanfan approved these changes

2021-08-23 05:20 UTC, merged