Add debug logging to telnet commands for minicircuits attenuator; revert #771
google/mobly pull request #772
Opened 2021-11-19 20:58 UTC by xianyuanjia

2021-11-20 06:29 UTC, xpconanfan requested changes
Revert the change and add logging in separate PR

2021-11-20 06:29 UTC, xpconanfan commented on mobly/controllers/attenuator_lib/telnet_scpi_client.py
> +    logging.debug('Telnet Command: {}'.format(cmd_str))
use logging's own string formatting instead

2021-11-24 01:22 UTC, xpconanfan requested changes

2021-11-24 01:22 UTC, xpconanfan commented on mobly/controllers/attenuator_lib/telnet_scpi_client.py
> +    logging.debug('Telnet Command: %s', cmd_str)
let's log these info in one line to be consistent with the other cmd logging patterns in Mobly, like `adb`

2021-11-24 01:59 UTC, xianyuanjia reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/google/mobly/772#-:-MpEen8r9elf1vMaOS8C:b-896fix)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @xianyuanjia and @xpconanfan)

___
*[mobly/controllers/attenuator_lib/telnet_scpi_client.py, line 76 at r1](https://reviewable.io/reviews/google/mobly/772#-MotzdsBUa5ZL0To77xA-r1-76:-MpEej2IDbOeu_SMtXW0:b-896fix) ([raw file](https://github.com/google/mobly/blob/9dfb013d7c1e35d6475229e8714f2399d6b99acc/mobly/controllers/attenuator_lib/telnet_scpi_client.py#L76)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

use logging's own string formatting instead
</blockquote></details>

Done.
___
*[mobly/controllers/attenuator_lib/telnet_scpi_client.py, line 76 at r2](https://reviewable.io/reviews/google/mobly/772#-MotzdsBUa5ZL0To77xA-r2-76:-MpEeieg6bDlEqOHFbHd:b-896fix) ([raw file](https://github.com/google/mobly/blob/9f3b97292f92be5cbd8d52a3ab95084c985dec6a/mobly/controllers/attenuator_lib/telnet_scpi_client.py#L76)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

let's log these info in one line to be consistent with the other cmd logging patterns in Mobly, like `adb`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 05:15 UTC, xpconanfan commented
We don't need this any more?

2022-02-08 19:32 UTC, xianyuanjia commented
It is no longer needed. Closing.

2022-02-08 19:32 UTC, closed without merging