Rename the `setup_generated_tests` stage to `pre_run`.
google/mobly pull request #844
Opened 2022-07-28 20:39 UTC by xpconanfan

Users have identified more legit use cases where operations before
`setup_class` are needed. The `setup_generated_tests` stage is
essentially the stage before `setup_class`.

Hence we are renaming it more properly.

2022-07-28 22:39 UTC, booneng approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eric100lin and @mhaoli)



<!-- Sent from Reviewable.io -->

2022-07-29 03:49 UTC, mhaoli submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eric100lin)



<!-- Sent from Reviewable.io -->

2022-07-29 18:01 UTC, eric100lin requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/844)* status: all files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[`mobly/base_test.py` line 41 at r1](https://reviewable.io/reviews/google/mobly/844#-N8A5jh2DyOGT9vKTXj0:-N8A5jh2DyOGT9vKTXj1:bybfcua) ([raw file](https://github.com/google/mobly/blob/94ca08b7f0645a69458402fa76c7906915d74f98/mobly/base_test.py#L41)):*
> ```Python
> STAGE_NAME_PRE_RUN = 'pre_run'
> # Deprecated, use `STAGE_NAME_PRE_RUN` instead.
> STAGE_NAME_SETUP_GENERATED_TESTS = 'setup_generated_tests'
> ```

It seems we no longer log stage with this deprecated name, in other word, you seems not using this stage name in base_test.py. Consider to remove it?



_Code quote:_
```Python
STAGE_NAME_SETUP_GENERATED_TESTS
```


<!-- Sent from Reviewable.io -->

2022-07-29 18:12 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly/844#-:-N8A9DZN-WoKmIWrFBwr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2022-08-01 19:54 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/844)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @booneng, @eric100lin, @mhaoli, and @xpconanfan)

___
*[`mobly/base_test.py` line 41 at r1](https://reviewable.io/reviews/google/mobly/844#-N8A5jh2DyOGT9vKTXj0:-N8A9cvt1Q1vpETEPHRt:b-a226wr) ([raw file](https://github.com/google/mobly/blob/94ca08b7f0645a69458402fa76c7906915d74f98/mobly/base_test.py#L41)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

It seems we no longer log stage with this deprecated name, in other word, you seems not using this stage name in base_test.py. Consider to remove it?
</blockquote></details>

Will remove in the next next release with the other code related to `setup_generated_tests`, per the  deprecation convention for public APIs



_Code quote:_
```Python
STAGE_NAME_SETUP_GENERATED_TESTS
```


<!-- Sent from Reviewable.io -->

2022-08-01 20:00 UTC, booneng approved these changes
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/844)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)



<!-- Sent from Reviewable.io -->

2022-08-01 20:02 UTC, merged