Always create the `AndroidDevice` object specific log directory.
google/mobly pull request #848
Opened 2022-08-02 20:35 UTC by xpconanfan

`AndroidDevice#log_path` is not always created, but it's accessible by user code.
This is ok most of the time because `logcat_service` is usually used.

2022-08-02 20:39 UTC, xpconanfan commented
Windows CI is broken. Need to fix

2022-08-05 20:53 UTC, xpconanfan commented
This is ready for review

2022-08-14 07:23 UTC, mhaoli submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/848)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @eric100lin)



<!-- Sent from Reviewable.io -->

2022-08-16 04:19 UTC, eric100lin requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/848)* status: all files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[`mobly/controllers/android_device.py` line 498 at r2](https://reviewable.io/reviews/google/mobly/848#-N9ZpMaC5xXaX8dSsWLb:-N9ZpMaC5xXaX8dSsWLc:b-217ii6) ([raw file](https://github.com/google/mobly/blob/975b119d23c6eda8b7dc8b7bd58e966de3c8c13b/mobly/controllers/android_device.py#L498)):*
> ```Python
>                                   'AndroidDevice%s' % self._normalized_serial)
>     utils.create_dir(self._log_path)
>     self._debug_tag = self._serial
> ```

As offline discussion, we might only keep one of the `utils.create_dir` in `log_path`



_Code quote:_
```Python
utils.create_dir(self._log_path)
```


<!-- Sent from Reviewable.io -->

2022-08-16 05:10 UTC, xpconanfan reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/848)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @eric100lin)

___
*[`mobly/controllers/android_device.py` line 498 at r2](https://reviewable.io/reviews/google/mobly/848#-N9ZpMaC5xXaX8dSsWLb:-N9_1k4D1KJ_OPhttvmG:b-896fix) ([raw file](https://github.com/google/mobly/blob/975b119d23c6eda8b7dc8b7bd58e966de3c8c13b/mobly/controllers/android_device.py#L498)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

As offline discussion, we might only keep one of the `utils.create_dir` in `log_path`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 05:53 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/848#-:-N9_Ccho4NE8EtJ2PduI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eric100lin)



<!-- Sent from Reviewable.io -->

2022-08-16 05:53 UTC, eric100lin approved these changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/848)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2022-08-16 05:54 UTC, merged