Don't mutate BaseTestClass.record_data() argument.
google/mobly pull request #856
Opened 2022-12-05 17:48 UTC by wolverdude

Mutating the argument can lead to weird results when mocking out the method for testing user code.

2022-12-05 19:57 UTC, xpconanfan approved these changes

2022-12-05 19:58 UTC, xpconanfan requested changes
Actually, can you add a unit test to validate this behavior?
Should be straightforward :)

2022-12-06 18:49 UTC, wolverdude commented on tests/mobly/base_test_test.py
>          self.assertIsNotNone(c['timestamp'])
This line would fail with an IndexError instead of an AssertionError if timestamp were missing, which is why I added the line above.

2022-12-07 06:22 UTC, xpconanfan approved these changes

2022-12-07 06:25 UTC, merged