Fix unhandling of possible recursion error on `ExceptionRecord.__deepcopy__`
google/mobly pull request #870
Opened 2023-02-06 16:25 UTC by uael

While using mobly and aio gRPC, the following very long trace pop on gRPC aio error. Although this might not be Mobly related, since `deepcopy` can trigger a `RecursionError` I think it make sense to handle it. This change fix that.

Trace (cut for readability):
```
AioRpcError
[ExampleTest] 02-06 15:47:34.895 ERROR Exception happened when executing on_fail for test.
Traceback (most recent call last):
  File "venv/lib/python3.10/site-packages/mobly/base_test.py", line 640, in _exec_procedure_func
    func(copy.deepcopy(tr_record))
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "venv/lib/python3.10/site-packages/mobly/records.py", line 280, in __deepcopy__
    exception = copy.deepcopy(self.exception)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.10/copy.py", line 264, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.10/copy.py", line 264, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  ...
RecursionError: maximum recursion depth exceeded  
 ```

2023-02-06 18:21 UTC, xpconanfan requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/870)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @uael)

___
*[`mobly/records.py` line 280 at r1](https://reviewable.io/reviews/google/mobly/870#-NNbx4868XxnFDd3Zezh:-NNbx4868XxnFDd3Zezi:b-b8utga) ([raw file](https://github.com/google/mobly/blob/5c82f439c51abc1db29e79de632d73338cbec7cb/mobly/records.py#L280)):*
> ```Python
>     try:
>       exception = copy.deepcopy(self.exception)
>     except (TypeError, RecursionError):
> ```

can you share the data that cause this to be raised?
I'm not sure if the same logic is correct for handling `RecursionError`, so let's take a look at the root cause to be sure

Also, we should have unit tests to cover this case :)


<!-- Sent from Reviewable.io -->

2023-02-06 19:26 UTC, uael commented
After some more investigation here we what's going on.

The [AioRpcError](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L60) from `grpcio` has what I see has a bogus initialization by passing `self` to the base constructor which actually create a self recursive exception:
> [`python/grpcio/grpc/aio/_call.py:89`](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L89)
> ```py
>     def __init__(self, ...):
>         super().__init__(self)
> ```

The `RecursionError` would have been raised here if [`__str__` was not overridden](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L145):
> [`mobly/records.py:248`](https://github.com/google/mobly/blob/master/mobly/records.py#L248)
> ```py
>     else:
>       self._set_details(e)
> ```

It's raising in the `deepcopy` instead:
> [`mobly/records.py:279`](https://github.com/google/mobly/blob/master/mobly/records.py#L279)
> ```py
>     try:
>       exception = copy.deepcopy(self.exception)
>     except TypeError:
> ```

Even if the recursion is clearly a bug in `grpcio` (I'm gonna open PR for it), since nothing prevent an error to be recursive, I still think this change to be relevant.

> I'm not sure if the same logic is correct for handling RecursionError
I think using the exception as is fine too since it cannot be copied.

I also just added a specific unit test.
Here is the `pytest` trace of the added test without the fix:
```py
======================================================================================================================================== FAILURES ========================================================================================================================================
__________________________________________________________________________________________________________________ RecordsTest.test_recursive_exception_record_deepcopy __________________________________________________________________________________________________________________

self = <tests.mobly.records_test.RecordsTest testMethod=test_recursive_exception_record_deepcopy>

    def test_recursive_exception_record_deepcopy(self):
      """Makes sure ExceptionRecord wrapper handles deep copy properly in case of recursive exception."""
      try:
        raise RecordTestRecursiveError()
      except RecordTestRecursiveError as e:
        er = records.ExceptionRecord(e)
>     new_er = copy.deepcopy(er)

tests/mobly/records_test.py:450: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.10/copy.py:153: in deepcopy
    y = copier(memo)
mobly/records.py:279: in __deepcopy__
    exception = copy.deepcopy(self.exception)
/usr/lib/python3.10/copy.py:172: in deepcopy
    y = _reconstruct(x, memo, *rv)
/usr/lib/python3.10/copy.py:265: in _reconstruct
    y = func(*args)
/usr/lib/python3.10/copy.py:264: in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
/usr/lib/python3.10/copy.py:172: in deepcopy
    y = _reconstruct(x, memo, *rv)
E   RecursionError: maximum recursion depth exceeded while calling a Python object
!!! Recursion detected (same locals & position)
```

2023-02-08 21:42 UTC, xpconanfan approved these changes

2023-02-15 01:35 UTC, xpconanfan commented on tests/mobly/records_test.py
> +    """Makes sure ExceptionRecord wrapper handles deep copy properly in case of recursive exception."""
pls make sure the line stays within line length limit of 80 chars

2023-02-15 01:35 UTC, xpconanfan approved these changes

2023-02-15 01:41 UTC, xpconanfan approved these changes

2023-02-15 01:43 UTC, uael reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/870)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @uael and @xpconanfan)

___
*[`mobly/records.py` line 280 at r1](https://reviewable.io/reviews/google/mobly/870#-NNbx4868XxnFDd3Zezh:-NOHjFnbATuNhFXQW0cU:b-896fix) ([raw file](https://github.com/google/mobly/blob/5c82f439c51abc1db29e79de632d73338cbec7cb/mobly/records.py#L280)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

can you share the data that cause this to be raised?
I'm not sure if the same logic is correct for handling `RecursionError`, so let's take a look at the root cause to be sure

Also, we should have unit tests to cover this case :)
</blockquote></details>

Done.
___
*[`tests/mobly/records_test.py` line 444 at r2](https://reviewable.io/reviews/google/mobly/870#-NNcBGNRnWv4wUef4zT8-r2-444:-NOHjHKO7PAjLJBN_7wq:b-896fix) ([raw file](https://github.com/google/mobly/blob/ab738ff80cfb1ee686f8a0099a7bfae2c49888e8/tests/mobly/records_test.py#L444)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

pls make sure the line stays within line length limit of 80 chars
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 01:56 UTC, merged