record: only write complete yaml to test summary file
google/mobly pull request #872
Opened 2023-02-28 21:52 UTC by uael

While trying to handle test events in real-time, by reading additions the test summary file, I encountered incomplete `yaml` data.
The following change might fix that behavior.

2023-02-28 22:31 UTC, xpconanfan commented
Is it possible to create a "unit test" to demonstrate this bug and validate the fix at the same time?

2023-03-02 01:44 UTC, xpconanfan requested changes
This PR is now very different from the first patch. Why?

2023-03-02 16:23 UTC, uael commented
I just updated the branch :+1:
I will open shortly a new PR with the other changes

2023-03-02 17:06 UTC, xpconanfan approved these changes

2023-03-02 17:07 UTC, merged