record: add `TestClassList` to emitted records
google/mobly pull request #873
Opened 2023-03-02 17:02 UTC by uael

When running multiple test classes in the test runner, it actually emit multiple `TestNameList` but one `Summary`. Which make impossible for a reader of the summary file to retrieve the complete list of tests before they had been executed.

To solve this a `TestClassList` record is now emitted before the run, which contains the full list of tests in the following format:
```yaml
Classes:
- Name: Foo
  Tests:
  - test_a
  - test_b
- Name: Bar
  Tests:
  - test_c
  - test_d
```

It was chosen to add a new record and to to not change the actual `TestNameList` record to not break the actual behavior.

2023-03-02 17:04 UTC, xpconanfan commented
This is a more involved change, which would have worked better if a design discussion were held beforehand

2023-03-02 17:05 UTC, xpconanfan requested changes

2023-03-02 17:05 UTC, xpconanfan commented on mobly/base_test.py
> +    # be called by `get_test_names` before `run`.
this is actually intentional

2023-03-02 17:09 UTC, uael commented
> This is a more involved change, which would have worked better if a design discussion were held beforehand

Sounds good to me :+1:
I was not very sure how to proceed on this one, I will be happy to follow the right process.

2023-03-15 19:01 UTC, uael commented
Closing this one in favor of #875.

2023-03-15 19:01 UTC, closed without merging