Fix utils.stop_standing_subprocess error on Mac OS
google/mobly pull request #920
Opened 2024-05-09 03:30 UTC by mhaoli

Forked from #916.

Now `utils.stop_standing_subprocess` uses some arguments of `ps` which is only supported on Linux, but not on Mac OS. So we need to use `pgrep` instead.

Also fixed the issue that unit tests did not check status of the subprocesses which should be killed.

2024-05-09 03:40 UTC, eric100lin requested changes
> *[Reviewable](https://reviewable.io/reviews/google/mobly/920)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mhaoli and @xpconanfan)

___
*[`mobly/utils.py` line 303 at r1](https://reviewable.io/reviews/google/mobly/920#-NxQR1p7DbLxSu0FJM5d:-NxQR1p7DbLxSu0FJM5e:b-elmd3q) ([raw file](https://github.com/google/mobly/blob/b3e5074826c80af2f7ee792d2697fad1d4ddf777/mobly/utils.py#L303)):*
> ```Python
>             .decode()
>             .strip()
>         )
> ```

Consider extracting the command as a variable and initializing it based on `platform.system()` to minimize the amount of code within a try/except block.



_Code quote:_
```Python
      if platform.system() == 'Darwin':
        ps_results = (
            subprocess.check_output(
                [
                    'pgrep',
                    '-P',
                    str(pid),
                ]
            )
            .decode()
            .strip()
        )
      else:
        ps_results = (
            subprocess.check_output(
                [
                    'ps',
                    '-o',
                    'pid',
                    '--ppid',
                    str(pid),
                    '--noheaders',
                ]
            )
            .decode()
            .strip()
        )
```


<!-- Sent from Reviewable.io -->

2024-05-10 07:59 UTC, mhaoli reviewed
> *[Reviewable](https://reviewable.io/reviews/google/mobly/920)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @eric100lin and @xpconanfan)

___
*[`mobly/utils.py` line 303 at r1](https://reviewable.io/reviews/google/mobly/920#-NxQR1p7DbLxSu0FJM5d:-NxWVrvY6D_NyYJn_rKg:b-53ngzo) ([raw file](https://github.com/google/mobly/blob/b3e5074826c80af2f7ee792d2697fad1d4ddf777/mobly/utils.py#L303)):*
<details><summary><i>Previously, eric100lin (Eric Lin (Tzu Hsiang Lin)) wrote…</i></summary><blockquote>

Consider extracting the command as a variable and initializing it based on `platform.system()` to minimize the amount of code within a try/except block.
</blockquote></details>

Thanks. Improved this to use `pgrep`for both Mac OS and Linux. So this problem does not exist.


<!-- Sent from Reviewable.io -->

2024-05-10 08:01 UTC, xpconanfan reviewed
what about windows?

2024-05-11 00:54 UTC, mhaoli commented
> what about windows?

Windows is handled by other logic. 

As in docstring, this function `_collect_process_tree` will only be used on unix like system bc windows process kill command handles all subprocesses automatically.

2024-05-11 04:44 UTC, xpconanfan approved these changes

2024-05-13 03:40 UTC, eric100lin approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/920#-:-Nxk1JxuDTGrNIqpYmW7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mhaoli)



<!-- Sent from Reviewable.io -->

2024-05-13 06:31 UTC, merged