Include k-v pairs from device config as `user_added_info` by default.
google/mobly pull request #935
Opened 2024-08-20 23:26 UTC by xpconanfan

Since these k-v pairs are added by users through the device config, by definition these are `user_added_info`. So they should be part of the `user_added_info` field of `device_info`.

2024-08-20 23:29 UTC, xianyuanjia submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/google/mobly/935#-:-O4m70lp14WGy71ymQ7X:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2024-08-21 23:20 UTC, xianyuanjia requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/935)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xpconanfan)

___
*[`mobly/controllers/android_device.py` line 142 at r2](https://reviewable.io/reviews/google/mobly/935#-O4rDkVOCULFC-LcM0A0:-O4rDkVOCULFC-LcM0A1:b2erph9) ([raw file](https://github.com/google/mobly/blob/0c6d4ae15f856307b7a405f98457c78a96d27ade/mobly/controllers/android_device.py#L142)):*
> ```Python
>   Returns:
>     A list of dict, each representing info for an AndroidDevice objects.
>     Everything in this dict should be yaml serializable.
> ```

The docstring of `add_device_info` also mentions that the info being added should be serializable.

I think we should sanitize the info directly in `add_device_info`. 


<!-- Sent from Reviewable.io -->

2024-08-22 00:12 UTC, xpconanfan commented
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/google/mobly/935)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @xpconanfan)
> 
> _[`mobly/controllers/android_device.py` line 142 at r2](https://reviewable.io/reviews/google/mobly/935#-O4rDkVOCULFC-LcM0A0:-O4rDkVOCULFC-LcM0A1:b2erph9) ([raw file](https://github.com/google/mobly/blob/0c6d4ae15f856307b7a405f98457c78a96d27ade/mobly/controllers/android_device.py#L142)):_
> 
> > ```python
> >   Returns:
> >     A list of dict, each representing info for an AndroidDevice objects.
> >     Everything in this dict should be yaml serializable.
> > ```
> 
> The docstring of `add_device_info` also mentions that the info being added should be serializable.
> 
> I think we should sanitize the info directly in `add_device_info`.

Serializable doesn't mean it's safe for yaml dump...
Also serializable doesn't mean it has to be normalized to a string.

So we want to stringify it as late as possible without adding module specific code to controller manager.

2024-08-22 00:17 UTC, xianyuanjia approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/mobly/935#-:-O4rRT6tC1SkIdhwPObQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @xpconanfan)



<!-- Sent from Reviewable.io -->

2024-08-22 17:30 UTC, merged